project:
  type: website
  output-dir: docs

website:
  title: "tagnon"
  reader-mode: true
  back-to-top-navigation: true
  repo-url: https://github.com/amenalahassa/amenalahassa
  repo-actions: [issue]
  sidebar:
    style: "floating"
    search: false
    contents:
      - href: index.qmd
        text: Blog
      - href: about.qmd
        text: L'auteur
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/alkonrad/
  page-footer:
    center: "Copyright 2024"

format:
  html:
    theme: morph
    toc: true
    anchor-sections: true
    smooth-scroll: true

format-links: [ipynb]
lang: fr

execute:
  freeze: auto