project:
  type: website
  output-dir: docs

website:
  title: "multiverse"
  reader-mode: true
  open-graph: true
  back-to-top-navigation: true
  description: "A small space in the vast universe of the Internet where I share the ideas and knowledge I've gained on my journey into AI and software development."
  site-url: "https://amenalahassa.github.io/amenalahassa/"
  repo-url: "https://github.com/amenalahassa/amenalahassa"
  repo-actions: [issue]
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Blog
      - href: works.qmd
        text: My works
      - href: about.qmd
        text: L'auteur
    tools:
      - icon: linkedin
        href: "https://www.linkedin.com/in/alkonrad/"
  page-footer:
    center: "Copyright 2024"
  twitter-card:
    creator: "@amenalahassa"
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-X5E8KFGB6H"
    anonymize-ip: true




format:
  html:
    theme: solar
    toc: true
    anchor-sections: true
    smooth-scroll: true
    css: assets/styles.css
    fig-cap-location: margin

format-links: [ipynb]
lang: fr

execute:
  freeze: auto