---
title: "Konrad Tagnon Amen ALAHASSA"
about:
    template: solana
    links:
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/alkonrad/
      - icon: github
        text: Github
        href: https://github.com/amenalahassa/amenalahassa
      - icon: email
        text: Say 👋!
        href: email:am.konrad21@gmail.com
---

AI Developer fluent in machine learning and web technologies, I'm passionate about leveraging AI to tackle real-world problems and create a tangible impact. My primary interests lie in revolutionizing industries such as food production and finance through innovative technological solutions. With a deep commitment to sharing knowledge and fostering collaboration, I actively contribute to open-source projects and engage with the tech community.

## Experiences

##### Lead Developer | Sept 2022 - Jul 2023
| *AgroSfer | Cotonou, Bénin*
Lead development teams in the creation of a dynamic data aggregation system to feed analytical dashboards.

##### Front-end Developer | Jun 2021 - Sept 2022
| *AgroSfer | Cotonou, Bénin*
Client-side component development with JavaScript, Angular, and Web API integration to optimize user interactions.

##### Internship in Web Development	 | Mars 2021 - Mai 2021
| *La Vedette Media Digital |  Cotonou, Bénin*
Design and development of the architecture for an intranet-based project management web platform for La Vedette Media.

##### Internship in Web Development	 | June 2020 - Sept 2020
| *NAUTILUS TECHNOLOGY  |  Cotonou, Bénin*
Internship role focusing on web development using JavaScript, Angular, Laravel, and Git, solidifying foundational web development skills.

## Skills

##### *Artificial Intelligence*
| Python, Pytorch, Tensorflow, Keras
| Matplotlib, Seaborn, Numpy, Pandas, timm, fastai, torchvision, Poutyne
SPSS Modeler, RStudio

##### *Software engineering*
| PHP, Javascript, C, C++, Java
| Angular, ReactJs, VueJs, Cypress, Web API
SQL, Mysql, Firebase, MongoDB

##### *Others*
DevOps, CI/CD, UX Design, Scrum, Agile


## Education

##### Maîtrise en informatique - Intelligence Artificielle | Since Sept 2023
| *Université Laval  | Québec, CA*
Pursuing a Master's degree focusing on Artificial Intelligence, enhancing skills in complex AI systems and machine learning implementations.


##### Systèmes informatiques et Logiciels | Oct 2018 - Jul 2021
| *Les COURS SONOU | Abomey-Calavi, Bénin*
Studied advanced software systems, focusing on practical and theoretical aspects of software engineering in Benin.


##### Baccalauréat Science Maths | Août 2018
| *CEG Application  | Porto-Novo, Bénin*
Graduated with a focus on Mathematics and Science, forming a strong analytical foundation.


## Online courses

##### From Engineer to Technical Manager: A Survival Guide, Sundog Education
| *Udemy - 2023*

## Interests
AI, Software Engineering, Web Development, Reading, Traveling, Music, Movies, Animes, Swimming, Hiking, BasketBall, and Learning new things.
